-- ============================================================
-- Sample Data for Fenix Commerce Platform
-- This script inserts test data for development and testing
-- ============================================================

-- Note: Replace these UUIDs with actual ones generated by your application
-- These are just examples showing the data structure

-- Sample Tenant 1
INSERT INTO tenant (tenant_id, tenant_name, status, created_at, updated_at)
VALUES (
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  'Acme Corporation',
  'ACTIVE',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Tenant 2
INSERT INTO tenant (tenant_id, tenant_name, status, created_at, updated_at)
VALUES (
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440001', 1),
  'Global Retail Inc',
  'ACTIVE',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Store for Tenant 1
INSERT INTO store (store_id, tenant_id, store_code, store_name, platform, timezone, currency, status, created_at, updated_at)
VALUES (
  UUID_TO_BIN('650e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  'ACME-SHOPIFY',
  'Acme Shopify Store',
  'SHOPIFY',
  'America/New_York',
  'USD',
  'ACTIVE',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Store for Tenant 1 (Second store)
INSERT INTO store (store_id, tenant_id, store_code, store_name, platform, timezone, currency, status, created_at, updated_at)
VALUES (
  UUID_TO_BIN('650e8400-e29b-41d4-a716-446655440001', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  'ACME-MAGENTO',
  'Acme Magento Store',
  'MAGENTO',
  'America/New_York',
  'USD',
  'ACTIVE',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Store for Tenant 2
INSERT INTO store (store_id, tenant_id, store_code, store_name, platform, timezone, currency, status, created_at, updated_at)
VALUES (
  UUID_TO_BIN('650e8400-e29b-41d4-a716-446655440002', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440001', 1),
  'GLOBAL-NETSUITE',
  'Global NetSuite Store',
  'NETSUITE',
  'Europe/London',
  'GBP',
  'ACTIVE',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Order 1
INSERT INTO orders (
  order_id,
  tenant_id,
  store_id,
  external_order_id,
  external_order_number,
  order_status,
  financial_status,
  fulfillment_status,
  customer_email,
  order_total_amount,
  currency,
  order_created_at,
  order_updated_at,
  ingested_at
) VALUES (
  UUID_TO_BIN('750e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('650e8400-e29b-41d4-a716-446655440000', 1),
  'SHOPIFY-12345',
  'ORD-2024-001',
  'CREATED',
  'PAID',
  'UNFULFILLED',
  'john.doe@example.com',
  129.99,
  'USD',
  '2024-01-15 10:30:00',
  '2024-01-15 10:30:00',
  CURRENT_TIMESTAMP
);

-- Sample Order 2
INSERT INTO orders (
  order_id,
  tenant_id,
  store_id,
  external_order_id,
  external_order_number,
  order_status,
  financial_status,
  fulfillment_status,
  customer_email,
  order_total_amount,
  currency,
  order_created_at,
  order_updated_at,
  ingested_at
) VALUES (
  UUID_TO_BIN('750e8400-e29b-41d4-a716-446655440001', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('650e8400-e29b-41d4-a716-446655440000', 1),
  'SHOPIFY-12346',
  'ORD-2024-002',
  'CREATED',
  'PAID',
  'PARTIAL',
  'jane.smith@example.com',
  249.50,
  'USD',
  '2024-01-16 14:20:00',
  '2024-01-16 14:20:00',
  CURRENT_TIMESTAMP
);

-- Sample Order Items for Order 1
INSERT INTO order_items (
  order_item_id,
  tenant_id,
  order_id,
  external_line_item_id,
  sku,
  title,
  quantity_ordered,
  unit_price,
  created_at,
  updated_at
) VALUES (
  UUID_TO_BIN('850e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('750e8400-e29b-41d4-a716-446655440000', 1),
  'LINE-001',
  'SKU-WIDGET-001',
  'Premium Widget',
  2,
  59.99,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT INTO order_items (
  order_item_id,
  tenant_id,
  order_id,
  external_line_item_id,
  sku,
  title,
  quantity_ordered,
  unit_price,
  created_at,
  updated_at
) VALUES (
  UUID_TO_BIN('850e8400-e29b-41d4-a716-446655440001', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('750e8400-e29b-41d4-a716-446655440000', 1),
  'LINE-002',
  'SKU-GADGET-001',
  'Smart Gadget',
  1,
  10.01,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Fulfillment for Order 1
INSERT INTO fulfillments (
  fulfillment_id,
  tenant_id,
  order_id,
  external_fulfillment_id,
  fulfillment_status,
  carrier,
  service_level,
  ship_from_location,
  shipped_at,
  delivered_at,
  created_at,
  updated_at
) VALUES (
  UUID_TO_BIN('950e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('750e8400-e29b-41d4-a716-446655440000', 1),
  'SHIP-001',
  'SHIPPED',
  'FedEx',
  '2-Day',
  'Warehouse A, New York',
  '2024-01-16 09:00:00',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Tracking for Fulfillment
INSERT INTO tracking (
  tracking_id,
  tenant_id,
  fulfillment_id,
  tracking_number,
  tracking_url,
  carrier,
  tracking_status,
  is_primary,
  last_event_at,
  created_at,
  updated_at
) VALUES (
  UUID_TO_BIN('a50e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('950e8400-e29b-41d4-a716-446655440000', 1),
  '1Z999AA10123456784',
  'https://www.fedex.com/track?tracknumbers=1Z999AA10123456784',
  'FedEx',
  'IN_TRANSIT',
  TRUE,
  '2024-01-16 15:30:00',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

-- Sample Tracking Events
INSERT INTO tracking_events (
  tracking_event_id,
  tenant_id,
  tracking_id,
  event_time,
  event_code,
  event_description,
  event_city,
  event_state,
  event_country,
  event_zip,
  source,
  event_hash,
  created_at
) VALUES (
  UUID_TO_BIN('b50e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('a50e8400-e29b-41d4-a716-446655440000', 1),
  '2024-01-16 09:00:00',
  'PICKED_UP',
  'Package picked up by carrier',
  'New York',
  'NY',
  'USA',
  '10001',
  'CARRIER',
  SHA2('550e8400-e29b-41d4-a716-446655440000|a50e8400-e29b-41d4-a716-446655440000|2024-01-16 09:00:00|PICKED_UP', 256),
  CURRENT_TIMESTAMP
);

INSERT INTO tracking_events (
  tracking_event_id,
  tenant_id,
  tracking_id,
  event_time,
  event_code,
  event_description,
  event_city,
  event_state,
  event_country,
  event_zip,
  source,
  event_hash,
  created_at
) VALUES (
  UUID_TO_BIN('b50e8400-e29b-41d4-a716-446655440001', 1),
  UUID_TO_BIN('550e8400-e29b-41d4-a716-446655440000', 1),
  UUID_TO_BIN('a50e8400-e29b-41d4-a716-446655440000', 1),
  '2024-01-16 15:30:00',
  'IN_TRANSIT',
  'Package in transit',
  'Philadelphia',
  'PA',
  'USA',
  '19019',
  'CARRIER',
  SHA2('550e8400-e29b-41d4-a716-446655440000|a50e8400-e29b-41d4-a716-446655440000|2024-01-16 15:30:00|IN_TRANSIT', 256),
  CURRENT_TIMESTAMP
);

-- Query to verify data
SELECT
  BIN_TO_UUID(t.tenant_id, 1) as tenant_uuid,
  t.tenant_name,
  COUNT(DISTINCT s.store_id) as store_count,
  COUNT(DISTINCT o.order_id) as order_count
FROM tenant t
LEFT JOIN store s ON t.tenant_id = s.tenant_id
LEFT JOIN orders o ON t.tenant_id = o.tenant_id
GROUP BY t.tenant_id, t.tenant_name;
